# Generated by Django 3.1.6 on 2021-05-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'О студии',
                'verbose_name_plural': 'О студии',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера')),
                ('positions', models.CharField(help_text='например: тату-мастер', max_length=70, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('about_master', models.TextField(verbose_name='О мастере')),
                ('vk_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Вконтакте')),
                ('inst_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Инстаграм')),
                ('telegram_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Телеграм')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TattooCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории тату для главной страницы')),
                ('content', models.TextField(help_text='Краткое описание про вид татуировок', max_length=500, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Вид татуировки',
                'verbose_name_plural': 'Виды татуировок',
            },
        ),
        migrations.CreateModel(
            name='WorkMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Не обязательно, не где не задействуется! Пример: ', max_length=50, null=True, verbose_name='Название тату')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('master_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_master', to='mainapp.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Работа мастера',
                'verbose_name_plural': 'Работа мастеров',
                'ordering': ['master_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название поста')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('views', models.IntegerField(default=0, verbose_name='Колличество просмотров')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.master', verbose_name='Имя мастера')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='mainapp.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
