# Generated by Django 3.1.6 on 2021-03-06 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'О студии',
                'verbose_name_plural': 'О студии',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера')),
                ('positions', models.CharField(blank=True, max_length=30, null=True, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('about_master', models.TextField(blank=True, help_text='Не обязательно!', null=True, verbose_name='О мастере')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TattooCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории тату для главной страницы')),
                ('content', models.CharField(help_text='Краткое описание про вид татуировок', max_length=250, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Вид татуировки',
                'verbose_name_plural': 'Виды татуировок',
            },
        ),
        migrations.CreateModel(
            name='WorkMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Не обязательно, не где не задействуется! Пример: Имя Фамилия мастера', max_length=50, null=True, verbose_name='Название тату')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('master_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_master', to='mainapp.master', verbose_name='Мастер')),
                ('tag', models.ManyToManyField(to='mainapp.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Работа мастера',
                'verbose_name_plural': 'Работа мастеров',
                'ordering': ['master_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название поста')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('views', models.IntegerField(default=0, verbose_name='Колличество просмотров')),
                ('image', models.ImageField(blank=True, help_text='Не обязательно!', null=True, upload_to='', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.master', verbose_name='Имя мастера')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='mainapp.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
