# Generated by Django 3.1.6 on 2021-03-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='positions',
        ),
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.CharField(blank=True, help_text='Не обязательно!', max_length=100, null=True, verbose_name='Опыт работы'),
        ),
    ]
