# Generated by Django 3.1.6 on 2021-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='master',
            name='inst_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Инстаграм'),
        ),
        migrations.AddField(
            model_name='master',
            name='vk_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Вконтакте'),
        ),
        migrations.AlterField(
            model_name='master',
            name='positions',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Должность'),
        ),
    ]
