# Generated by Django 3.1.6 on 2021-05-08 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmaster',
            name='tag',
        ),
        migrations.AddField(
            model_name='master',
            name='inst_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Инстаграм'),
        ),
        migrations.AddField(
            model_name='master',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Телеграм'),
        ),
        migrations.AddField(
            model_name='master',
            name='vk_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Вконтакте'),
        ),
        migrations.AddField(
            model_name='workmaster',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='about_master',
            field=models.TextField(verbose_name='О мастере'),
        ),
        migrations.AlterField(
            model_name='master',
            name='positions',
            field=models.CharField(help_text='например: тату-мастер', max_length=70, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tattoocategory',
            name='content',
            field=models.TextField(help_text='Краткое описание про вид татуировок', max_length=500, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='workmaster',
            name='name',
            field=models.CharField(blank=True, help_text='Не обязательно, не где не задействуется! Пример: ', max_length=50, null=True, verbose_name='Название тату'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
