# Generated by Django 3.1.6 on 2021-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='image',
            field=models.ImageField(upload_to='masters/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='workmaster',
            name='image',
            field=models.ImageField(upload_to='work_master/', verbose_name='Изображение'),
        ),
    ]
