# Generated by Django 3.1.6 on 2021-05-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210513_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='workmaster',
            name='name',
            field=models.CharField(blank=True, help_text='Не обязательно, не где не задействуется! Пример: a-z, 0-9. любые рандомные значения', max_length=50, null=True, verbose_name='Название тату'),
        ),
    ]
