# Generated by Django 3.1.6 on 2021-04-01 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210401_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmaster',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
