# Generated by Django 3.1.6 on 2021-03-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210306_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
