# Generated by Django 3.1.6 on 2021-03-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210306_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='experience',
            new_name='positions',
        ),
    ]
