# Generated by Django 3.1.6 on 2021-04-03 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_workmaster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
