# Generated by Django 3.1.6 on 2021-04-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_client_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
