# Generated by Django 3.1.6 on 2021-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210306_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='positions',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Должность'),
        ),
    ]
