# Generated by Django 3.1.6 on 2021-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmaster',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
    ]
