# Generated by Django 3.1.6 on 2021-03-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210306_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='inst_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Инстаграм'),
        ),
        migrations.AddField(
            model_name='master',
            name='vk_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Вконтакте'),
        ),
    ]
