# Generated by Django 3.1.6 on 2021-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210405_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Телеграм'),
        ),
        migrations.AlterField(
            model_name='master',
            name='about_master',
            field=models.TextField(verbose_name='О мастере'),
        ),
        migrations.AlterField(
            model_name='master',
            name='positions',
            field=models.CharField(help_text='например: тату-мастер', max_length=70, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Не обязательно!', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='workmaster',
            name='name',
            field=models.CharField(blank=True, help_text='Не обязательно, не где не задействуется! Пример: ', max_length=50, null=True, verbose_name='Название тату'),
        ),
    ]
