# Generated by Django 3.1.6 on 2021-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210420_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoocategory',
            name='content',
            field=models.TextField(help_text='Краткое описание про вид татуировок', max_length=500, verbose_name='Контент'),
        ),
    ]
