# Generated by Django 3.1.6 on 2021-04-04 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_send', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
