# Generated by Django 3.1.6 on 2021-05-08 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_send', '0004_remove_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=250, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
