# Generated by Django 3.1.6 on 2021-05-07 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_send', '0005_auto_20210404_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
